[package]
name = "thrasybulus"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.35.0"
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
rusqlite = { version = "0.32.0", features = ["bundled", "chrono"] }
chrono = "0.4.38"